/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiErrorMessage: typeof import('./components/feedback/ApiErrorMessage.vue')['default']
    AuthShell: typeof import('./components/auth/AuthShell.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmAction: typeof import('./components/feedback/ConfirmAction.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EmptyTable: typeof import('./components/data/EmptyTable.vue')['default']
    EntityDrawerShell: typeof import('./components/shell/EntityDrawerShell.vue')['default']
    FloatingConfigurator: typeof import('./components/FloatingConfigurator.vue')['default']
    FormDialogShell: typeof import('./components/shell/FormDialogShell.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PagedTable: typeof import('./components/data/PagedTable.vue')['default']
    PageShell: typeof import('./components/shell/PageShell.vue')['default']
    PageState: typeof import('./components/feedback/PageState.vue')['default']
    PageToolbar: typeof import('./components/data/PageToolbar.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SensitiveActionDialog: typeof import('./components/shell/SensitiveActionDialog.vue')['default']
    SettingField: typeof import('./components/forms/SettingField.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SurfaceCard: typeof import('./components/shell/SurfaceCard.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface GlobalDirectives {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
