"""initial schema

Revision ID: b2802c046144
Revises:
Create Date: 2026-08-07 08:19:10.205863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b2802c046144"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_roles",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "assets_objects",
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("bucket", sa.String(length=200), nullable=True),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=200), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=128), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("asset_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("external_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_key", "object_key", name="uq_assets_provider_object"),
    )
    op.create_table(
        "assets_upload_intents",
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("content_length_max", sa.Integer(), nullable=False),
        sa.Column("mime_types", sa.String(length=500), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_table(
        "audit_entries",
        sa.Column("envelope_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=200), nullable=True),
        sa.Column("client_id", sa.String(length=200), nullable=True),
        sa.Column("session_handle", sa.String(length=200), nullable=True),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=200), nullable=True),
        sa.Column("request_id", sa.String(length=200), nullable=True),
        sa.Column("trace_id", sa.String(length=200), nullable=True),
        sa.Column("correlation_id", sa.String(length=200), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("envelope_id"),
    )
    op.create_index(op.f("ix_audit_entries_action"), "audit_entries", ["action"], unique=False)
    op.create_index(op.f("ix_audit_entries_actor_id"), "audit_entries", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_entries_occurred_at"), "audit_entries", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_audit_entries_window", "audit_entries", ["occurred_at", "action"], unique=False
    )
    op.create_table(
        "contents",
        sa.Column("type_name", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("owner_type", sa.String(length=32), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("pin_rank", sa.Integer(), nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("schedule_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status != 'published' OR published_at IS NOT NULL",
            name="ck_contents_published_requires_time",
        ),
        sa.CheckConstraint(
            "status != 'scheduled' OR publish_at IS NOT NULL",
            name="ck_contents_scheduled_requires_time",
        ),
        sa.CheckConstraint(
            "status NOT IN ('draft', 'pending', 'rejected', 'archived') OR publish_at IS NULL",
            name="ck_contents_schedule_consistent",
        ),
        sa.CheckConstraint("pin_rank >= 0 AND pin_rank <= 999", name="ck_contents_pin_rank_range"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_name", "slug", name="uq_contents_type_slug"),
    )
    op.create_index("ix_contents_due_scheduled", "contents", ["status", "publish_at"], unique=False)
    op.create_index(op.f("ix_contents_owner_id"), "contents", ["owner_id"], unique=False)
    op.create_index(
        "ix_contents_pin_order", "contents", ["is_pinned", "pin_rank", "published_at"], unique=False
    )
    op.create_index(op.f("ix_contents_status"), "contents", ["status"], unique=False)
    op.create_index(op.f("ix_contents_type_name"), "contents", ["type_name"], unique=False)
    op.create_table(
        "identity_users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("username_normalized", sa.String(length=100), nullable=False),
        sa.Column("email_display", sa.String(length=320), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("avatar_asset_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_normalized"),
        sa.UniqueConstraint("username_normalized"),
    )
    op.create_table(
        "kernel_cron_state",
        sa.Column("cron_key", sa.String(length=200), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cron_key", name="uq_kernel_cron_state_key"),
    )
    op.create_table(
        "kernel_inbox_receipts",
        sa.Column("handler_key", sa.String(length=200), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "handler_key", "event_id", name="uq_kernel_inbox_receipts_handler_event"
        ),
    )
    op.create_index(
        "ix_kernel_inbox_receipts_handler", "kernel_inbox_receipts", ["handler_key"], unique=False
    )
    op.create_table(
        "kernel_outbox",
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("envelope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_category", sa.String(length=32), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "ix_kernel_outbox_due", "kernel_outbox", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(
        op.f("ix_kernel_outbox_event_key"), "kernel_outbox", ["event_key"], unique=False
    )
    op.create_table(
        "kernel_task_instances",
        sa.Column("task_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timeout_seconds", sa.Float(), nullable=False),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_category", sa.String(length=32), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kernel_task_due", "kernel_task_instances", ["status", "next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_kernel_task_instances_task_key"),
        "kernel_task_instances",
        ["task_key"],
        unique=False,
    )
    op.create_table(
        "kernel_workflow_instances",
        sa.Column("workflow_key", sa.String(length=200), nullable=False),
        sa.Column("workflow_version", sa.String(length=32), nullable=False),
        sa.Column("business_idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_step", sa.String(length=200), nullable=True),
        sa.Column("step_attempt", sa.Integer(), nullable=False),
        sa.Column("wake_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.String(length=200), nullable=True),
        sa.Column("trace_id", sa.String(length=200), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_key", "business_idempotency_key", name="uq_kernel_workflow_idempotency"
        ),
    )
    op.create_index(
        "ix_kernel_workflow_due", "kernel_workflow_instances", ["status", "wake_at"], unique=False
    )
    op.create_index(
        op.f("ix_kernel_workflow_instances_workflow_key"),
        "kernel_workflow_instances",
        ["workflow_key"],
        unique=False,
    )
    op.create_table(
        "oidc_authorization_codes",
        sa.Column("code_digest", sa.String(length=128), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("redirect_uri", sa.String(length=500), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audiences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nonce", sa.String(length=500), nullable=True),
        sa.Column("code_challenge", sa.String(length=200), nullable=True),
        sa.Column("code_challenge_method", sa.String(length=16), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_digest"),
    )
    op.create_index(
        op.f("ix_oidc_authorization_codes_client_id"),
        "oidc_authorization_codes",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oidc_authorization_codes_subject_id"),
        "oidc_authorization_codes",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "oidc_client_secrets",
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("secret_digest", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oidc_client_secrets_client_id"), "oidc_client_secrets", ["client_id"], unique=False
    )
    op.create_table(
        "oidc_clients",
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("client_type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("redirect_uris", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "post_logout_redirect_uris", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("allowed_scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_audiences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("auth_method", sa.String(length=32), nullable=False),
        sa.Column("grant_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("allow_refresh", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
    )
    op.create_table(
        "oidc_grants_consents",
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audiences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_id", "client_id", name="uq_oidc_grant_subject_client"),
    )
    op.create_index(
        op.f("ix_oidc_grants_consents_client_id"),
        "oidc_grants_consents",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oidc_grants_consents_subject_id"),
        "oidc_grants_consents",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "oidc_refresh_families",
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oidc_refresh_families_client_id"),
        "oidc_refresh_families",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oidc_refresh_families_subject_id"),
        "oidc_refresh_families",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "oidc_sessions",
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("session_handle", sa.String(length=128), nullable=False),
        sa.Column("auth_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acr", sa.String(length=32), nullable=False),
        sa.Column("amr", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_handle"),
    )
    op.create_index(
        op.f("ix_oidc_sessions_client_id"), "oidc_sessions", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_oidc_sessions_subject_id"), "oidc_sessions", ["subject_id"], unique=False
    )
    op.create_table(
        "oidc_signing_keys",
        sa.Column("kid", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=16), nullable=False),
        sa.Column("public_jwk", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("not_before_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delete_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kid"),
    )
    op.create_index("ix_oidc_signing_keys_status", "oidc_signing_keys", ["status"], unique=False)
    op.create_table(
        "settings_values",
        sa.Column("group_key", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_key"),
    )
    op.create_table(
        "taxonomy_dimensions",
        sa.Column("dimension_key", sa.String(length=100), nullable=False),
        sa.Column("spec_version", sa.String(length=32), nullable=False),
        sa.Column("selection_mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dimension_key"),
    )
    op.create_table(
        "taxonomy_terms",
        sa.Column("dimension_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("term_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dimension_key", "slug", name="uq_taxonomy_terms_dimension_slug"),
    )
    op.create_index(
        op.f("ix_taxonomy_terms_dimension_key"), "taxonomy_terms", ["dimension_key"], unique=False
    )
    op.create_table(
        "access_role_capabilities",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("capability_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["access_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "capability_key", name="uq_access_role_capability"),
    )
    op.create_index(
        op.f("ix_access_role_capabilities_role_id"),
        "access_role_capabilities",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "access_subject_roles",
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["access_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject_type", "subject_id", "role_id", name="uq_access_subject_role"),
    )
    op.create_index(
        op.f("ix_access_subject_roles_role_id"), "access_subject_roles", ["role_id"], unique=False
    )
    op.create_index(
        "ix_access_subject_roles_subject",
        "access_subject_roles",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.create_table(
        "content_references",
        sa.Column("source_content_id", sa.Uuid(), nullable=False),
        sa.Column("target_content_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("ref_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_content_id"], ["contents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_content_id"],
            ["contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_content_id",
            "target_content_id",
            "kind",
            name="uq_content_references_source_target_kind",
        ),
    )
    op.create_index(
        op.f("ix_content_references_source_content_id"),
        "content_references",
        ["source_content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_references_target_content_id"),
        "content_references",
        ["target_content_id"],
        unique=False,
    )
    op.create_table(
        "identity_challenges",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("token_digest", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["identity_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index(
        op.f("ix_identity_challenges_expires_at"),
        "identity_challenges",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_identity_challenges_purpose_digest",
        "identity_challenges",
        ["purpose", "token_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_challenges_user_id"), "identity_challenges", ["user_id"], unique=False
    )
    op.create_table(
        "identity_login_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_subject", sa.String(length=320), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["identity_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_identity_login_identity_provider_subject"
        ),
    )
    op.create_index(
        op.f("ix_identity_login_identities_user_id"),
        "identity_login_identities",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "identity_password_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("password_hash", sa.String(length=500), nullable=False),
        sa.Column("hash_version", sa.String(length=32), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("compromised_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["identity_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "kernel_workflow_signals",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("signal_key", sa.String(length=200), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["kernel_workflow_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_id", "signal_key", "signal_id", name="uq_kernel_workflow_signal"
        ),
    )
    op.create_index(
        "ix_kernel_workflow_signals_undelivered",
        "kernel_workflow_signals",
        ["workflow_id", "signal_key", "delivered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kernel_workflow_signals_workflow_id"),
        "kernel_workflow_signals",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "kernel_workflow_step_attempts",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("step_key", sa.String(length=200), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_category", sa.String(length=32), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("trace_id", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["kernel_workflow_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_id", "step_key", "attempt", name="uq_kernel_workflow_step_attempt"
        ),
    )
    op.create_index(
        op.f("ix_kernel_workflow_step_attempts_workflow_id"),
        "kernel_workflow_step_attempts",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "oidc_refresh_tokens",
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.String(length=128), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audiences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inactivity_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["oidc_refresh_families.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index(
        op.f("ix_oidc_refresh_tokens_family_id"), "oidc_refresh_tokens", ["family_id"], unique=False
    )
    op.create_table(
        "taxonomy_assignments",
        sa.Column("dimension_key", sa.String(length=100), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["term_id"], ["taxonomy_terms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dimension_key",
            "target_type",
            "target_id",
            "term_id",
            name="uq_taxonomy_assignments_target_term",
        ),
    )
    op.create_index(
        op.f("ix_taxonomy_assignments_target_id"),
        "taxonomy_assignments",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_taxonomy_assignments_term_id"), "taxonomy_assignments", ["term_id"], unique=False
    )
    op.create_index(
        "ix_taxonomy_assignments_term_target",
        "taxonomy_assignments",
        ["term_id", "target_type", "target_id"],
        unique=False,
    )

    op.create_table(
        "notification_intents",
        sa.Column("spec_key", sa.String(length=100), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("recipient_type", sa.String(length=32), nullable=False),
        sa.Column("recipient_id", sa.String(length=200), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "spec_key", "idempotency_key", name="uq_notification_intents_spec_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_notification_intents_recipient_id"),
        "notification_intents",
        ["recipient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_intents_spec_key"), "notification_intents", ["spec_key"], unique=False
    )
    op.create_table(
        "notification_templates",
        sa.Column("template_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("body", sa.String(length=5000), nullable=False),
        sa.Column("variables_schema_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "template_key",
            "version",
            "channel",
            "locale",
            name="uq_notification_templates_key_version_channel_locale",
        ),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("intent_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("recipient", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_ref", sa.String(length=200), nullable=True),
        sa.Column("error_category", sa.String(length=32), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["intent_id"], ["notification_intents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_deliveries_due",
        "notification_deliveries",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_intent_id"),
        "notification_deliveries",
        ["intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_status"),
        "notification_deliveries",
        ["status"],
        unique=False,
    )

    op.create_table(
        "payment_orders",
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("order_reference", sa.String(length=200), nullable=False),
        sa.Column("offer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_amount", sa.Integer(), nullable=False),
        sa.Column("refunded_amount", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_reference"),
        sa.UniqueConstraint(
            "provider_key", "idempotency_key", name="uq_payment_orders_provider_idempotency"
        ),
    )
    op.create_index(op.f("ix_payment_orders_state"), "payment_orders", ["state"], unique=False)
    op.create_index(
        op.f("ix_payment_orders_subject_id"), "payment_orders", ["subject_id"], unique=False
    )
    op.create_table(
        "points_behavior_definitions",
        sa.Column("behavior_key", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("program_key", sa.String(length=100), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("behavior_key"),
    )
    op.create_table(
        "points_programs",
        sa.Column("program_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("allow_admin_reversal", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_key"),
    )
    op.create_table(
        "payment_attempts",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("provider_ref", sa.String(length=200), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("request_digest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_category", sa.String(length=32), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["payment_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_attempts_order_id"), "payment_attempts", ["order_id"], unique=False
    )
    op.create_table(
        "payment_refunds",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("refund_ref", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["payment_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "idempotency_key", name="uq_payment_refunds_order_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_payment_refunds_order_id"), "payment_refunds", ["order_id"], unique=False
    )
    op.create_table(
        "payment_webhook_receipts",
        sa.Column("provider_key", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=200), nullable=False),
        sa.Column("payload_digest", sa.String(length=128), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_state", sa.String(length=16), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_key", "event_id", name="uq_payment_webhook_provider_event"),
    )
    op.create_index(
        op.f("ix_payment_webhook_receipts_order_id"),
        "payment_webhook_receipts",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "points_accounts",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["points_programs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "program_id", "subject_type", "subject_id", name="uq_points_accounts_program_subject"
        ),
    )
    op.create_index(
        op.f("ix_points_accounts_program_id"), "points_accounts", ["program_id"], unique=False
    )
    op.create_index(
        op.f("ix_points_accounts_subject_id"), "points_accounts", ["subject_id"], unique=False
    )
    op.create_table(
        "points_balances",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["points_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id"),
    )
    op.create_table(
        "points_ledger_entries",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(length=16), nullable=False),
        sa.Column("behavior_key", sa.String(length=200), nullable=True),
        sa.Column("behavior_version", sa.String(length=32), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=True),
        sa.Column("source_id", sa.String(length=200), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("actor_type", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=200), nullable=True),
        sa.Column("entry_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reversal_of", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["points_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["points_programs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["points_ledger_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "program_id", "idempotency_key", name="uq_points_ledger_program_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_points_ledger_entries_account_id"),
        "points_ledger_entries",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_points_ledger_entries_program_id"),
        "points_ledger_entries",
        ["program_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_points_ledger_entries_reversal_of"),
        "points_ledger_entries",
        ["reversal_of"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_points_ledger_entries_reversal_of"), table_name="points_ledger_entries")
    op.drop_index(op.f("ix_points_ledger_entries_program_id"), table_name="points_ledger_entries")
    op.drop_index(op.f("ix_points_ledger_entries_account_id"), table_name="points_ledger_entries")
    op.drop_table("points_ledger_entries")
    op.drop_table("points_balances")
    op.drop_index(op.f("ix_points_accounts_subject_id"), table_name="points_accounts")
    op.drop_index(op.f("ix_points_accounts_program_id"), table_name="points_accounts")
    op.drop_table("points_accounts")
    op.drop_index(
        op.f("ix_payment_webhook_receipts_order_id"), table_name="payment_webhook_receipts"
    )
    op.drop_table("payment_webhook_receipts")
    op.drop_index(op.f("ix_payment_refunds_order_id"), table_name="payment_refunds")
    op.drop_table("payment_refunds")
    op.drop_index(op.f("ix_payment_attempts_order_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_table("points_programs")
    op.drop_table("points_behavior_definitions")
    op.drop_index(op.f("ix_payment_orders_subject_id"), table_name="payment_orders")
    op.drop_index(op.f("ix_payment_orders_state"), table_name="payment_orders")
    op.drop_table("payment_orders")

    op.drop_index(op.f("ix_notification_deliveries_status"), table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_intent_id"), table_name="notification_deliveries"
    )
    op.drop_index("ix_notification_deliveries_due", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("notification_templates")
    op.drop_index(op.f("ix_notification_intents_spec_key"), table_name="notification_intents")
    op.drop_index(op.f("ix_notification_intents_recipient_id"), table_name="notification_intents")
    op.drop_table("notification_intents")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_taxonomy_assignments_term_target", table_name="taxonomy_assignments")
    op.drop_index(op.f("ix_taxonomy_assignments_term_id"), table_name="taxonomy_assignments")
    op.drop_index(op.f("ix_taxonomy_assignments_target_id"), table_name="taxonomy_assignments")
    op.drop_table("taxonomy_assignments")
    op.drop_index(op.f("ix_oidc_refresh_tokens_family_id"), table_name="oidc_refresh_tokens")
    op.drop_table("oidc_refresh_tokens")
    op.drop_index(
        op.f("ix_kernel_workflow_step_attempts_workflow_id"),
        table_name="kernel_workflow_step_attempts",
    )
    op.drop_table("kernel_workflow_step_attempts")
    op.drop_index(
        op.f("ix_kernel_workflow_signals_workflow_id"), table_name="kernel_workflow_signals"
    )
    op.drop_index("ix_kernel_workflow_signals_undelivered", table_name="kernel_workflow_signals")
    op.drop_table("kernel_workflow_signals")
    op.drop_table("identity_password_credentials")
    op.drop_index(
        op.f("ix_identity_login_identities_user_id"), table_name="identity_login_identities"
    )
    op.drop_table("identity_login_identities")
    op.drop_index(op.f("ix_identity_challenges_user_id"), table_name="identity_challenges")
    op.drop_index("ix_identity_challenges_purpose_digest", table_name="identity_challenges")
    op.drop_index(op.f("ix_identity_challenges_expires_at"), table_name="identity_challenges")
    op.drop_table("identity_challenges")
    op.drop_index(op.f("ix_content_references_target_content_id"), table_name="content_references")
    op.drop_index(op.f("ix_content_references_source_content_id"), table_name="content_references")
    op.drop_table("content_references")
    op.drop_index("ix_access_subject_roles_subject", table_name="access_subject_roles")
    op.drop_index(op.f("ix_access_subject_roles_role_id"), table_name="access_subject_roles")
    op.drop_table("access_subject_roles")
    op.drop_index(
        op.f("ix_access_role_capabilities_role_id"), table_name="access_role_capabilities"
    )
    op.drop_table("access_role_capabilities")
    op.drop_index(op.f("ix_taxonomy_terms_dimension_key"), table_name="taxonomy_terms")
    op.drop_table("taxonomy_terms")
    op.drop_table("taxonomy_dimensions")
    op.drop_table("settings_values")
    op.drop_index("ix_oidc_signing_keys_status", table_name="oidc_signing_keys")
    op.drop_table("oidc_signing_keys")
    op.drop_index(op.f("ix_oidc_sessions_subject_id"), table_name="oidc_sessions")
    op.drop_index(op.f("ix_oidc_sessions_client_id"), table_name="oidc_sessions")
    op.drop_table("oidc_sessions")
    op.drop_index(op.f("ix_oidc_refresh_families_subject_id"), table_name="oidc_refresh_families")
    op.drop_index(op.f("ix_oidc_refresh_families_client_id"), table_name="oidc_refresh_families")
    op.drop_table("oidc_refresh_families")
    op.drop_index(op.f("ix_oidc_grants_consents_subject_id"), table_name="oidc_grants_consents")
    op.drop_index(op.f("ix_oidc_grants_consents_client_id"), table_name="oidc_grants_consents")
    op.drop_table("oidc_grants_consents")
    op.drop_table("oidc_clients")
    op.drop_index(op.f("ix_oidc_client_secrets_client_id"), table_name="oidc_client_secrets")
    op.drop_table("oidc_client_secrets")
    op.drop_index(
        op.f("ix_oidc_authorization_codes_subject_id"), table_name="oidc_authorization_codes"
    )
    op.drop_index(
        op.f("ix_oidc_authorization_codes_client_id"), table_name="oidc_authorization_codes"
    )
    op.drop_table("oidc_authorization_codes")
    op.drop_index(
        op.f("ix_kernel_workflow_instances_workflow_key"), table_name="kernel_workflow_instances"
    )
    op.drop_index("ix_kernel_workflow_due", table_name="kernel_workflow_instances")
    op.drop_table("kernel_workflow_instances")
    op.drop_index(op.f("ix_kernel_task_instances_task_key"), table_name="kernel_task_instances")
    op.drop_index("ix_kernel_task_due", table_name="kernel_task_instances")
    op.drop_table("kernel_task_instances")
    op.drop_index(op.f("ix_kernel_outbox_event_key"), table_name="kernel_outbox")
    op.drop_index("ix_kernel_outbox_due", table_name="kernel_outbox")
    op.drop_table("kernel_outbox")
    op.drop_index("ix_kernel_inbox_receipts_handler", table_name="kernel_inbox_receipts")
    op.drop_table("kernel_inbox_receipts")
    op.drop_table("kernel_cron_state")
    op.drop_table("identity_users")
    op.drop_index(op.f("ix_contents_type_name"), table_name="contents")
    op.drop_index(op.f("ix_contents_status"), table_name="contents")
    op.drop_index("ix_contents_pin_order", table_name="contents")
    op.drop_index(op.f("ix_contents_owner_id"), table_name="contents")
    op.drop_index("ix_contents_due_scheduled", table_name="contents")
    op.drop_table("contents")
    op.drop_index("ix_audit_entries_window", table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_occurred_at"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_actor_id"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_action"), table_name="audit_entries")
    op.drop_table("audit_entries")
    op.drop_table("assets_upload_intents")
    op.drop_table("assets_objects")
    op.drop_table("access_roles")
