[program:backend]
command=/opt/venv/bin/uvicorn inc.main:get_app --factory --host 127.0.0.1 --port 8000
directory=/app
user=aiya
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=aiya
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
stopsignal=QUIT
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
